Escribe un programa que cree un array unidimensional con los enteros positivos 
múti�plos de 4 menores que 100.

In [248]:
import numpy as np

np.arange(0,100,4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

Escribe un programa que cree un array bidimensional de 5 filas y 4 columnas con los 
enteros desde 0 hasta 19.

In [102]:
import numpy as np

np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Escribe un programa que invierte el orden de los elementos de un array unidimensional.

In [112]:
import numpy as np

x = np.arange(20)
inverter = np.flip(x)
print(inverter)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

Escribe un programa que invierte el orden de las filas de un array bidimensional.

In [117]:
import numpy as np

x = np.arange(20).reshape(5,4)
inverter = np.flipud(x)
inverter

[[16 17 18 19]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


Escribe un programa que calcule la media de los elementos de cada columna de un 
array bidimensional.

In [138]:
import numpy as np

x = np.arange(20).reshape(5,4)
print(np.mean(x, axis=0))

[ 8.  9. 10. 11.]


Escribe un programa que redimensione un array unidimensional a un array bidimensional con 4 filas y 3 columnas.

In [247]:
import numpy as np

vector = np.arange(12)
array_2d = np.reshape(vector, (4,3))

print(vector)
print(array_2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Escribe un programa que, dado un array unidimensional, compruebe si se puede redimensionar a un array bidimensional con el mismo número de filas y columnas (matriz cuadrada). En caso afirmativo, debe imprimir la matriz cuadrada. En caso negativo, debe imprimir un mensaje informativo.

In [246]:
import numpy as np

vector = np.arange(25)
nElements = vector.size
dimension = int(np.sqrt(nElements))

if dimension * dimension == nElements:
    matrix = np.reshape(vector, (dimension,dimension))
    print(matrix)
else:
    print("No se puede crear una matriz cuadrada")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Escribe un programa que, dado un array bidimensional, halle el máximo de cada fila.

In [236]:
import numpy as np

matrix = np.random.randint(0, 100, (5,4))

print(matrix)
print(np.max(matrix, axis=1))

[[50 34 94  1]
 [19 33 64 42]
 [ 1 71  3 15]
 [ 9 55 29 82]
 [24 17 15 63]]
[94 64 71 82 63]


Escribe un programa que, dado un array unidimensional, halle el número de veces que 
aparece cada uno de sus elementos únicos.

In [255]:
import numpy as np

vector = np.array([1, 2, 3, 2, 4, 1, 3, 1, 4, 4, 5])

elementos_unicos, recuentos = np.unique(vector, return_counts=True)
print("Elementos únicos:", elementos_unicos)
print("Recuentos:", recuentos)

Elementos únicos: [1 2 3 4 5]
Recuentos: [3 2 2 3 1]


Normaliza un array bidimensional de 4 filas y 3 columnas restando la media y 
dividiendo por la desviacióntí�pica en cada columna.

In [276]:
import numpy as np

matrix = np.arange(12).reshape(4,3)
average = np.mean(matrix, axis=0)
dt = np.std(matrix, axis=0)
normalizeMatrix = (matrix - average) / dt

print(matrix)
print(average)
print(dt)
print(normalizeMatrix)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[4.5 5.5 6.5]
[3.35410197 3.35410197 3.35410197]
[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]


Normaliza un array bidimensional de 4 filas y 3 columnas restando la media y 
dividiendo por la desviacióntí�pica en cada fila.

In [283]:
import numpy as np

matrix = np.arange(12).reshape(4,3)
average = np.mean(matrix, axis=1).reshape((4,1))
dt = np.std(matrix, axis=1).reshape((4,1))
normalizeMatrix = (matrix - average) / dt

print(matrix)
print(average)
print(dt)
print(normalizeMatrix)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 1.]
 [ 4.]
 [ 7.]
 [10.]]
[[0.81649658]
 [0.81649658]
 [0.81649658]
 [0.81649658]]
[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


Escribe un programa que, dado un array bidimensional, halle los índices (filas y columnas) de los elementos mínimo y máximo del array.

In [300]:
import numpy as np

matrix = np.arange(12).reshape(4,3)
idxMax = np.unravel_index(np.argmax(matriz), matriz.shape)
idxMin = np.unravel_index(np.argmin(matriz), matriz.shape)

print(matrix)
print("Índices del elemento máximo:", idxMax)
print("Índices del elemento mínimo:", idxMin)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Índices del elemento máximo: (3, 2)
Índices del elemento mínimo: (0, 0)


Escribe un programa que ordene las filas de un array bidimensional según los valores 
de la primera columna.

In [344]:
import numpy as np

matrix = np.array([[10, 2, 1], [6, 5, 4], [9, 8, 7], [20, 5, 11]])
matriz_ordenada = matrix[matrix[:,0].argsort()]

print(matrix)
print(matriz_ordenada)


[[10  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [20  5 11]]
[[ 6  5  4]
 [ 9  8  7]
 [10  2  1]
 [20  5 11]]


Escribe un programa que genere una matriz bidimensional con 7 filas y 5 columnas 
aleatoriamente de acuerdo a la distribución normal, y a coti�nuación ponga a cer 
todos los elementos neti􀆟vos.

In [379]:
import numpy as np

matrix = np.random.normal(0,100,(7,5))
matrix[matrix < 0] = 0

print(matrix)

[[ 41.31618663  98.19879084   0.         255.00306387   0.        ]
 [  0.           0.          23.86493948  87.49314093   0.        ]
 [ 15.81346749 109.31079113   0.           5.08366815 112.3029395 ]
 [  0.           0.           0.          73.17092769 216.86516321]
 [ 37.8269857    0.           6.18154506   0.           2.62155158]
 [ 92.02194995   0.           0.           0.           0.        ]
 [  0.42032851   1.02033915 203.99540599  97.04431997   0.        ]]


Escribe un programa que, dado un array unidimensional y un número entero positivo k, 
halle los índices de los k mayores valores del array.

In [390]:
import numpy as np

vector = np.array([5, 2, 12, -1, 8, 6, 1, 9, 3, 7])

print(vector)
print(np.where(vector > 4))

[ 5  2 12 -1  8  6  1  9  3  7]
(array([0, 2, 4, 5, 7, 9], dtype=int64),)


Escribe un programa que genere una matriz bidimensional con 6 filas y 7 columnas aleatoriamente de acuerdo a la distribución uniforme, y a continuación ponga a cero las dos primeras columnas y a uno las tres últimas columnas.

In [421]:
import numpy as np

matrix = np.random.uniform(size=(6,7))
matrix[:,:2]=0
matrix[:,-3:]=1

print(matrix)

[[0.         0.         0.66011002 0.52504995 1.         1.
  1.        ]
 [0.         0.         0.42121169 0.64934339 1.         1.
  1.        ]
 [0.         0.         0.50581286 0.98626358 1.         1.
  1.        ]
 [0.         0.         0.77508602 0.707852   1.         1.
  1.        ]
 [0.         0.         0.90016043 0.31336479 1.         1.
  1.        ]
 [0.         0.         0.76361999 0.44578212 1.         1.
  1.        ]]
