Importamos numpy

In [1]:
import numpy as np

Creamos un array n_dimensional

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
x

array([1, 2, 3, 4, 5])

In [5]:
x.ndim

1

In [10]:
array_as_list = list(range(int(10e6)))
array_as_ndarray = np.array(array_as_list)
%timeit sum(array_as_list)
%timeit array_as_ndarray.sum()

292 ms ± 63.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
5.05 ms ± 463 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
array1 = np.array([88, 23, 39, 41])
array2 = np.array([[76.4, 21.7, 38.4],[41.2, 52.8, 68.9]])
array3 = np.array([[12],[4],[9],[8]])

In [26]:
array1.ndim

1

In [19]:
array1.size

4

In [20]:
array1.shape

(4,)

In [21]:
array1.dtype

dtype('int32')

In [24]:
print(array1)
print(array2)

[88 23 39 41]
[[76.4 21.7 38.4]
 [41.2 52.8 68.9]]


In [27]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
np.reshape(a, (3, 4)) # 3 x 4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
np.diag([5, 4, 3, 2, 1])

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [36]:
np.diag(range(50))

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       [ 0,  0,  2, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 47,  0,  0],
       [ 0,  0,  0, ...,  0, 48,  0],
       [ 0,  0,  0, ...,  0,  0, 49]])

Una matriz de 20 filas y 5 columnas con valores flotantes equiespaciados en el intervalo 
cerrado [1, 10].

In [52]:
matriz = np.linspace(1, 10, num=20*5).reshape(20, 5)
matriz

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636],
       [ 1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182],
       [ 1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727],
       [ 2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818],
       [ 3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364],
       [ 3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909],
       [ 4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ],
       [ 5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545],
       [ 5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091],
       [ 6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182],
       [ 6.90909091,  7.        ,  7.0

Un array unidimensional con 128 valores aleatorios de una distribución normal 𝜇 = 1, 𝜎 = 2.

In [53]:
dist = np.random.normal(1, 2, size=128)
dist

array([ 1.09331962e+00,  1.87486957e+00,  5.91736611e-01, -2.88204324e+00,
       -2.01132597e+00,  2.33745405e+00,  1.60475316e+00,  1.50648438e-01,
        3.03004910e+00, -5.91779532e-01,  2.47133895e+00,  3.39543858e+00,
       -2.14352221e+00,  4.94362408e+00, -1.10863142e+00,  2.33398527e+00,
       -1.95830725e+00,  1.12444079e+00,  1.11616015e+00,  5.26094894e+00,
        2.18562244e+00,  2.45965338e+00, -1.58041593e+00,  4.24385938e+00,
       -2.60581596e+00,  4.63707202e+00,  1.11284296e+00,  1.94966251e-01,
        1.57250608e+00,  5.11359274e+00,  1.97737445e+00,  2.23051632e+00,
        1.28952910e+00,  1.63745343e+00,  1.21338968e+00,  2.91750741e+00,
        1.67897806e+00,  5.20219931e-01, -7.01920614e-04,  3.50421720e+00,
        1.93405532e+00,  1.92309581e+00,  1.01240820e+00,  1.55180386e+00,
        3.76709529e+00, -1.93147066e+00,  4.22586579e+00,  9.78487415e-01,
       -3.01616269e-01,  2.40798978e+00,  1.52601161e+00,  5.06052310e-01,
        5.03470489e-01,  

Un array unidimensional con 15 valores aleatorios de una muestra 1, X, 2 donde la probabilidad de que gane el equipo local es del 50%, la probabilidad de que empaten es del 30% y la probabilidad de que gane el visitante es del 20%.

In [61]:
opciones = [1, 'X', 2]
probabilidades = [0.5, 0.3, 0.2]

array = np.random.choice(opciones, size=15, p=probabilidades)
array


array(['2', '1', '2', 'X', '2', '1', '1', 'X', '2', '1', '2', 'X', '2',
       '2', '1'], dtype='<U11')

In [63]:
values = np.arange(1, 13).reshape(3, 4)
values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
values[[0, 2], [1, 2]]

array([ 2, 11])

In [74]:
values[0:2, 0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [73]:
values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
values[0, 0] = 100
values

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [76]:
values[1] = [55, 66, 77, 88]
values

array([[100,   2,   3,   4],
       [ 55,  66,  77,  88],
       [  9,  10,  11,  12]])

In [77]:
values[:,2] = [30, 70, 110]
values

array([[100,   2,  30,   4],
       [ 55,  66,  70,  88],
       [  9,  10, 110,  12]])

In [78]:
np.delete(values, 0, axis=0)

array([[ 55,  66,  70,  88],
       [  9,  10, 110,  12]])

In [82]:
np.diag(values, -1)

array([55, 10])